### PR TITLE
Collect formulas.

### PR DESCRIPTION
**Pull request by kylemas**

### CODE REVIEW

**Comment by kylemas** [comment]
Notes: 
1. 2/3 test cases written are passing; the case where the 'tree does not branch' seems to be failing.
2. Tried doing console logs on the 'resolvedRows' variable (returned by the method I wrote) doesn't seem to be returning anything. 
3. Added a console log statement for inside the for-each loop in my method and it doesn't seem to be reaching that point as well. 

```
for (const idx of nodePath) {
    if (currentNode.nodeType !== 'formulas') {
      throw new Error('Failed to get node path')
    }

    currentNode.formulas.forEach((element) => {
      if (element.resolved) {
        resolvedRows.push(element.row)
        console.log("Element pushed")
      }
      console.log(resolvedRows)
    })
    currentNode = currentNode.forest[idx]
  }
```

**Comment by McTano** [comment]
Did you read my message on slack? I explained why it's not working.
The outer loop doesn't run when there's only a root node.

**Comment by kylemas** [comment]
Sorry, I didn't catch your last message on Slack! I made some changes and the test cases are passing now.

**Comment by McTano** [comment]
Good work!
Just to be safe, add a test case for the other case, where the tree does have more  than one node, but doesn't branch.
And make sure to remove all those console.logs.

**Comment by kylemas** [comment]
@McTano 
Done!

**Comment by kylemas** [comment]
@McTano 
Changed the input parameters in the RudolfReducer file! Should be working out now.

**Pull request merged**
